hh-back/hh_back/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('', lambda request: redirect('main/', permanent=True))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hh-back/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *

app_name = "main"
urlpatterns = [
    path('', main_page, name="main_page"),
    path('companies/', companies_list, name="companies_page"),
    path('companies/<int:comp_id>/', company_detail_page, name="company_detail"),
    path('vacancies/', vacancies_list, name="vacancies_page"),
    path('vacancies/<int:vac_id>/', vacancy_detail, name="vacancy_detail"),
    path('resumes/', resumes_list, name="resumes_page"),
    path('resumes/<int:res_id>/', resume_detail, name="resume_detail")
] + static(settings.MEDIA_URL, document_roo=settings.MEDIA_ROOT)

hh-back/main/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название Компании")
    description = models.TextField(verbose_name="Описание")
    city = models.CharField(max_length=100, verbose_name="Город")
    address = models.TextField(verbose_name="Адресс компании")

    def __str__(self):
        return f'{self.name} - {self.description}'


class Vacancy(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название Вакансии")
    description = models.TextField(verbose_name="Описание")
    salary = models.IntegerField(default=0, null=True, verbose_name="Зарплата")
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return f'Vacancy: {self.name}'


class Resumes(models.Model):
    name = models.CharField(max_length=200, verbose_name="Имя сотрудника")
    job_title = models.CharField(max_length=200, verbose_name="Специальность")
    city = models.CharField(max_length=100, verbose_name="Город проживания")
    expected_salary = models.IntegerField(default=0, null=True, verbose_name="Ожидаемая зарплата")
    job_experience = models.IntegerField(default=0, verbose_name="Опыт работы в годах")
    study_degree = models.CharField(max_length=200, null=True, verbose_name="Образование")
    description = models.TextField(null=True, verbose_name="Описание себя")
    email = models.CharField(max_length=200, verbose_name='Email', null=True)

    def __str__(self):
        return f"Имя: {self.name}, Специальность: {self.job_title}"

hh-back/main/forms.py
from django import forms

from .models import Vacancy


class VacancyForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = [
            'name', 'description', 'salary', 'company'
        ]

hh-back/main/views.py
from django.http.response import JsonResponse, HttpResponsePermanentRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import VacancyForm
from .models import *


def main_page(request):
    return HttpResponsePermanentRedirect("/main/vacancies/")


def authorize(request):
    return render(request, "main/auth.html", {})


def companies_list(request):
    companies = Company.objects.all()
    return render(request, "main/companies_index.html", {'companies': companies})


def company_detail_page(request, comp_id):
    try:
        company = Company.objects.get(id=comp_id)
        vacancies = Vacancy.objects.filter(company__pk=comp_id)
        if request.method == 'POST':
            d = {
                'name': request.POST['name'],
                'description': request.POST['description'],
                'salary': request.POST['salary'],
                'company': company
            }
            vacancy_form = VacancyForm(d)
            if vacancy_form.is_valid():
                vacancy_form.save()
            return redirect(reverse('main:company_detail', args=(comp_id,)))
    except Company.DoesNotExist as e:
        return JsonResponse({'Error': str(e)})
    return render(request, "main/company_detail.html", {'company': company, 'vacancies': vacancies})


def vacancies_list(request):
    vacancies = Vacancy.objects.all()
    return render(request, "main/vacancies_index.html", {'vacancies': vacancies})


def vacancy_detail(request, vac_id):
    try:
        vacancy = Vacancy.objects.get(id=vac_id)
    except Vacancy.DoesNotExist as e:
        return JsonResponse({'error': str(e)})

    return render(request, 'main/vacancy_detail.html', {'vacancy': vacancy})


def resumes_list(request):
    resumes = Resumes.objects.all()
    return render(request, "main/resumes_index.html", {'resumes': resumes})


def resume_detail(request, res_id):
    try:
        resume = Resumes.objects.get(id=res_id)
    except Resumes.DoesNotExist as e:
        return JsonResponse({'error': str(e)})

    return render(request, 'main/resume_detail.html', {'resume': resume})

hh-back/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale-1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
{% load static %}
<body class="container">
    <nav class="navbar navbar-expand-sm bg-light">
        <div class="row">
            <div class="col-sm-4">
                <a class="nav-link" href="{% url 'main:vacancies_page' %}">
                    <img alt="Course Logo" class="w-25 img-fluid" src="{% static 'main/img.png' %}">
                </a>
            </div>
        </div>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:vacancies_page' %}">Vacancies</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:resumes_page' %}">Resumes</a>
            </li>
        </ul>
    </nav>
    {% block content %}

    {% endblock %}
</body>
</html>

hh-back/main/templates/main/companies_index.html
{% extends "main/base.html" %}

{% block title %}
Companies Index
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h1 class="text-center display-4">Companies</h1>
                {% if companies %}
                    {% for company in companies %}
                    <div class="card">
                        <div class="card-body">
                            <h1 class="card-title">
                                <a href="{% url 'main:company_detail' company.pk %}">{{company.name}}</a>
                            </h1>
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Описание</td>
                                        <td>{{company.description}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="text-center">Нет вакансий</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

hh-back/main/templates/main/company_detail.html
{% extends "main/base.html" %}

{% block title %}
Company Detail
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">{{company.name}}</h1>
                <table class="table">
                    <tbody>
                        <tr>
                            <td>Город</td>
                            <td>{{company.city}}</td>
                        </tr>
                        <tr>
                            <td>Адресс</td>
                            <td>{{company.address}}</td>
                        </tr>
                        <tr>
                            <td>Описание</td>
                            <td>{{company.description}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% if vacancies|length > 0 %}
<div class="row">
    <div class="col-sm">
        <div class="card">
            <div class="card-body">
                <h6 class="text-center">Вакансии</h6>
                {% for vacancy in vacancies %}
                <p>Вакансия: <a href="{% url 'main:vacancy_detail' vacancy.pk %}">{{vacancy.name}}</a>
                    <br>Описание: {{vacancy.description}}</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-sm">
        <div class="card">
            <div class="card-body">
              <form class="form" enctype="multipart/form-data" method="post">
                  {% csrf_token %}
                  <input class="form-control mx-auto" name="name" placeholder="Название вакансии" style="width:50%" type="text">
                  <input class="form-control mx-auto" name="description" placeholder="Описание" style="width:50%" type="text">
                  <input class="form-control mx-auto" name="salary" style="width:50%" type="int">
                  <input class="btn btn-primary d-block mx-auto" style="width:50%" type="submit" value="Создать вакансию">
              </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

hh-back/main/templates/main/resume_detail.html
{% extends "main/base.html" %}


{% block title %}
Resume Detail
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">{{resume.name}}</h1>
                <table class="table">
                    <tbody>
                        <tr>
                            <td>{{resume.job_title}}</td>
                        </tr>
                        <tr>
                            <td>Зарплата</td>
                            <td>{{resume.expected_salary}} тг</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>{{resume.email}}</td>
                        </tr>
                        <tr>
                            <td>Город проживания</td>
                            <td>{{resume.city}}</td>
                        </tr>
                        <tr>
                            <td>Стаж работы</td>
                            <td>{{resume.job_experience}}</td>
                        </tr>
                        <tr>
                            <td>Образование</td>
                            <td>{{resume.study_degree}}</td>
                        </tr>
                        <tr>
                            <td>Описание</td>
                            <td>{{resume.description}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

hh-back/main/templates/main/resumes_index.html
{% extends "main/base.html" %}

{% block title %}
Resumes index
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h1 class="text-center display-4">Resumes</h1>
                {% if resumes %}
                    {% for resume in resumes %}
                    <div class="card">
                        <div class="card-body">
                            <h1 class="card-title">
                                <a href="{% url 'main:resume_detail' resume.pk %}">{{resume.name}}</a>
                            </h1>
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>{{resume.description}}</td>
                                    </tr>
                                    <tr>
                                        <td>Описание</td>
                                        <td>{{resume.description}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="text-center">Нет резюме</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

hh-back/main/templates/main/vacancies_index.html
{% extends "main/base.html" %}

{% block title %}
Vacancies index
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h1 class="text-center display-4">Vacancies</h1>
                {% if vacancies %}
                    {% for vacancy in vacancies %}
                    <div class="card">
                        <div class="card-body">
                            <h1 class="card-title">
                                <a href="{% url 'main:vacancy_detail' vacancy.pk %}">{{vacancy.name}}</a>
                            </h1>
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>{{vacancy.description}}</td>
                                    </tr>
                                    <tr>
                                        <td>Описание</td>
                                        <td>{{vacancy.description}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="text-center">Нет вакансий</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

hh-back/main/templates/main/vacancy_detail.html
{% extends "main/base.html" %}

{% block title %}
Company Detail
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">{{vacancy.name}}</h1>
                <table class="table">
                    <tbody>
                        <tr>
                            <td>Компания</td>
                            <td><a href="{% url 'main:company_detail' vacancy.company.pk %}">{{vacancy.company.name}}</a></td>
                        </tr>
                        <tr>
                            <td>Зарплата</td>
                            <td>{{vacancy.salary}} тг</td>
                        </tr>
                        <tr>
                            <td>Описание</td>
                            <td>{{vacancy.description}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}